apiVersion: v1
kind: Service
metadata:
  name: security-audit-service
  namespace: hse-llm-project
  labels:
    app: security-audit-service
spec:
  selector:
    app: security-audit-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
